# Generated by Django 5.2 on 2026-04-30 06:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoCurricularActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='cocurricular/')),
                ('is_active', models.BooleanField(default=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.school')),
            ],
        ),
        migrations.CreateModel(
            name='GalleryAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.school')),
            ],
        ),
        migrations.CreateModel(
            name='GalleryPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/')),
                ('caption', models.CharField(blank=True, max_length=300)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='website.galleryalbum')),
            ],
        ),
        migrations.CreateModel(
            name='NewsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('post_type', models.CharField(choices=[('news', 'News'), ('event', 'Event'), ('notice', 'Notice'), ('achievement', 'Achievement')], default='news', max_length=20)),
                ('content', models.TextField()),
                ('summary', models.CharField(blank=True, max_length=500)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='news/')),
                ('is_published', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.school')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ParentComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=200)),
                ('comment', models.TextField()),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.school')),
            ],
        ),
        migrations.CreateModel(
            name='KCSEResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('candidates_sat', models.IntegerField(default=0)),
                ('mean_grade', models.CharField(blank=True, max_length=5)),
                ('mean_points', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('university_qualifiers', models.IntegerField(default=0)),
                ('pass_rate', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('county_position', models.IntegerField(blank=True, null=True)),
                ('national_position', models.IntegerField(blank=True, null=True)),
                ('count_a_plain', models.IntegerField(default=0)),
                ('count_a_minus', models.IntegerField(default=0)),
                ('count_b_plus', models.IntegerField(default=0)),
                ('count_b_plain', models.IntegerField(default=0)),
                ('count_b_minus', models.IntegerField(default=0)),
                ('count_c_plus', models.IntegerField(default=0)),
                ('count_c_plain', models.IntegerField(default=0)),
                ('count_c_minus', models.IntegerField(default=0)),
                ('count_d_plus', models.IntegerField(default=0)),
                ('count_d_plain', models.IntegerField(default=0)),
                ('count_d_minus', models.IntegerField(default=0)),
                ('count_e', models.IntegerField(default=0)),
                ('top_student_name', models.CharField(blank=True, max_length=200)),
                ('top_student_grade', models.CharField(blank=True, max_length=5)),
                ('top_student_points', models.IntegerField(blank=True, null=True)),
                ('summary', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kcse_results', to='schools.school')),
            ],
            options={
                'ordering': ['-year'],
                'unique_together': {('school', 'year')},
            },
        ),
    ]
