# Generated by Django 5.1 on 2026-03-16 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="school_role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("super_admin", "Super Admin"),
                    ("principal", "Principal"),
                    ("bursar", "Bursar"),
                    ("dean", "Dean of Studies"),
                    ("admin", "General Admin"),
                ],
                default="admin",
                max_length=20,
            ),
        ),
    ]
