# Generated by Django 5.2 on 2026-04-27 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_school_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='school_role',
            field=models.CharField(blank=True, choices=[('super_admin', 'Super Admin'), ('principal', 'Principal'), ('bursar', 'Bursar'), ('dean', 'Dean of Studies'), ('secretary', 'Secretary'), ('admin', 'General Admin')], default='admin', max_length=20),
        ),
    ]
