# Generated by Django 5.2 on 2026-04-26 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='exam_paper',
            field=models.FileField(blank=True, help_text='Upload the exam paper (PDF, DOC, etc.)', null=True, upload_to='exam_papers/'),
        ),
    ]
